version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db